### ISSUE TITLE
Bot responding to the word help

### ISSUE THREAD

**Issue by ecclesiatech** [pastorhudson/pcobot#102]
On our general channel anytime someone uses the word help in a message (any message) the PCO bot responds.

**Comment by pastorhudson** [comment]
Hey @ecclesiatech are you on the latest master build? That was fixed in #81 . 
If you forked the repo, and did the install the old way you may want to start fresh using the "Deploy to Heroku button" This will keep your but updated with the latest changes. I test stuff on dev branch and try to only push to master once everything is working well.

**Comment by ecclesiatech** [comment]
Got it, will give it a try. How can we tell if we are on the latest build?

**Comment by ecclesiatech** [comment]
haha, I'm pretty sure I broke it at this point. Just started fresh with "Deploy to Heroku Button" and now can't seem to get it working. — Asher

**Comment by pastorhudson** [comment]
Woops lol. Make sure you put the right stuff in the heroku fields and it should work.

**Comment by pastorhudson** [comment]
Also make sure you setup the whitelist. If you don't whitelist channels it won't respond.

**Comment by pastorhudson** [comment]
Closing this up since it's fixed.
