### ISSUE TITLE
ACL Group Names

### ISSUE THREAD

**Issue by Chalta** [pastorhudson/pcobot#20]
I see that the ACL groups being defined are "Pastors" and "Staff".

Depending on how granular the permissions need to get, perhaps this could reflect PCO's permissions structure and use the term "administrators" and/or "schedulers" instead of "staff"? It's pedantic, but staff implies a paid employee, and some PCO schedulers may be trusted, senior volunteers.

I'll wait to hear back before making pull requests.

**Comment by pastorhudson** [comment]
@Chalta , I was thinking about this today. I started to do a complete overhaul of will bot's acl system. Because we need to be able to edit acl from slack or at least from userland rather than editing a config file. I think the best way to handle it would be to actually check planning center permissions against the slack user. We should be able to match up email address and name to pco users and check their permissions. If we can get this to work then willbot acl will only need to have administrators in it for backend stuff. Would you like to work on this?

**Comment by pastorhudson** [comment]
I'm going to take a stab at the planning center permissions integration. I'll leave this open so we can figure out what the default ACL groups for will-bot should be.

**Comment by pastorhudson** [comment]
I changed all Planning Center commands to check permission from planning center rather than use the will bot ACL. I also changed the default ACL:
```
ACL = {
    "admin": ["some_admin"],
}
```

Would you like to update the README?

**Comment by pastorhudson** [comment]
Updated. I'm closing this. @Chalta Feel free to make it better. I like the way you changed it last time :)
