### ISSUE TITLE
#general channel for announcements

### ISSUE THREAD

**Issue by ecclesiatech** [pastorhudson/pcobot#90]
Can we add functionality for posting announcements to #general channel or configure the channel for announcements?

**Comment by pastorhudson** [comment]
Yes. One guiding principle for pcobot should be that everything that is configurable should be configurable through slack. This is a pretty simple problem to fix since we have self.save and self.load in the WillPlugin. It would be a a great starter contribution if someone wants to take a stab at it.

**Comment by pastorhudson** [comment]
Fixed in #91
